# Generated by Django 2.1.3 on 2018-11-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='imagem',
            field=models.ImageField(default='servicos/default.png', upload_to='servicos/'),
        ),
    ]
