# Generated by Django 2.1.3 on 2018-11-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181126_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sobre',
            options={'verbose_name': 'Sobre', 'verbose_name_plural': 'Sobre'},
        ),
    ]
