# Generated by Django 2.1.3 on 2018-12-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181126_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.CharField(max_length=30, verbose_name='Frase para o banner inicial')),
            ],
        ),
        migrations.AlterField(
            model_name='servico',
            name='imagem',
            field=models.ImageField(default='servicos/default.png', upload_to='servicos/'),
        ),
    ]
