# Generated by Django 2.1.3 on 2018-12-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181126_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.TextField(verbose_name='Facebook')),
                ('instagram', models.TextField(verbose_name='Instagram')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Informações de Contato',
                'verbose_name_plural': 'Informações de Contato',
            },
        ),
    ]
