# Generated by Django 2.1.3 on 2018-12-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='gmaps',
            field=models.TextField(default='#', verbose_name='Link do Google Maps'),
        ),
        migrations.AddField(
            model_name='contato',
            name='local',
            field=models.TextField(default='Meu local no mundo', verbose_name='Localização'),
        ),
    ]
