# Generated by Django 2.1.3 on 2018-12-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181210_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='telefone',
            field=models.CharField(default='(00) 0.0000-0000', max_length=20),
        ),
    ]
