# Generated by Django 2.1.3 on 2018-12-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contato_telefone'),
        ('core', '0008_banner_imagem'),
    ]

    operations = [
    ]
