# Generated by Django 2.1.3 on 2018-12-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20181224_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'verbose_name': 'Informações de contato', 'verbose_name_plural': 'Informações de contato'},
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(default='meuemail@minhaempresa.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='facebook',
            field=models.TextField(default='http://fb.me/MinhaPagina', verbose_name='Pergil no Facebook'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='gmaps',
            field=models.TextField(default='https://goo.gl/maps/gN3aVB8nCzm', verbose_name='Link do Google Maps'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='instagram',
            field=models.TextField(default='instagram.com/MinhaPagina', verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
